# vim:set ft=tmux:
## name: Oasis Midnight Light 1
## author: uhs-robert

# Main
set -ogq @thm_primary_strong "#8c8643"
set -ogq @thm_primary "#696224"
set -ogq @thm_primary_light "#706612"
set -ogq @thm_secondary "#870606"
set -ogq @thm_prefix "#388032"
set -ogq @thm_fg "#181811"

# Surfaces and overlays
set -ogq @thm_core "#eceff4"
set -ogq @thm_crust "#e7ebf1"
set -ogq @thm_mantle "#dde3ec"
set -ogq @thm_surface "#c5cede"
set -ogq @thm_visual "#e1c99d"

# General
set -ogq @thm_red "#b81212"
set -ogq @thm_orange "#884e14"
set -ogq @thm_yellow "#645d21"
set -ogq @thm_green "#3a6636"
set -ogq @thm_teal "#366458"
set -ogq @thm_blue "#155da6"
set -ogq @thm_indigo "#7a26dc"
