# vim:set ft=tmux:
## name: Oasis Moonlight Light 1
## author: uhs-robert

# Main
set -ogq @thm_primary_strong "#40668e"
set -ogq @thm_primary "#2c4560"
set -ogq @thm_primary_light "#28425a"
set -ogq @thm_secondary "#786e14"
set -ogq @thm_prefix "#ab0707"
set -ogq @thm_fg "#181811"

# Surfaces and overlays
set -ogq @thm_core "#f3f2eb"
set -ogq @thm_crust "#f0efe6"
set -ogq @thm_mantle "#eae9dd"
set -ogq @thm_surface "#dcd9c5"
set -ogq @thm_visual "#e1b69d"

# General
set -ogq @thm_red "#bc1313"
set -ogq @thm_orange "#8a4f15"
set -ogq @thm_yellow "#665f22"
set -ogq @thm_green "#3b6837"
set -ogq @thm_teal "#37665a"
set -ogq @thm_blue "#155fa9"
set -ogq @thm_indigo "#7c2add"
