# vim:set ft=tmux:
## name: Oasis Twilight Light 1
## author: uhs-robert

# Main
set -ogq @thm_primary_strong "#a64a28"
set -ogq @thm_primary "#7f270d"
set -ogq @thm_primary_light "#77280b"
set -ogq @thm_secondary "#400687"
set -ogq @thm_prefix "#988c1a"
set -ogq @thm_fg "#1b1b13"

# Surfaces and overlays
set -ogq @thm_core "#f8f4fb"
set -ogq @thm_crust "#f4eef9"
set -ogq @thm_mantle "#ede3f5"
set -ogq @thm_surface "#dbc7eb"
set -ogq @thm_visual "#e1b69d"

# General
set -ogq @thm_red "#c01313"
set -ogq @thm_orange "#8d5115"
set -ogq @thm_yellow "#686123"
set -ogq @thm_green "#3c6a38"
set -ogq @thm_teal "#39695c"
set -ogq @thm_blue "#1561ad"
set -ogq @thm_indigo "#7e2edd"
