# vim:set ft=tmux:
## name: Oasis Scorpion Light 1
## author: uhs-robert

# Main
set -ogq @thm_primary_strong "#4b8846"
set -ogq @thm_primary "#2c6527"
set -ogq @thm_primary_light "#28631f"
set -ogq @thm_secondary "#7f270d"
set -ogq @thm_prefix "#857c2d"
set -ogq @thm_fg "#181811"

# Surfaces and overlays
set -ogq @thm_core "#f9e4dd"
set -ogq @thm_crust "#f8dfd6"
set -ogq @thm_mantle "#f6d5c9"
set -ogq @thm_surface "#f0bba9"
set -ogq @thm_visual "#e1b69d"

# General
set -ogq @thm_red "#b11212"
set -ogq @thm_orange "#824b13"
set -ogq @thm_yellow "#605a20"
set -ogq @thm_green "#386234"
set -ogq @thm_teal "#346054"
set -ogq @thm_blue "#14599f"
set -ogq @thm_indigo "#7522d6"
