# vim:set ft=tmux:
## name: Oasis Dune Light 1
## author: uhs-robert

# Main
set -ogq @thm_primary_strong "#8c7c43"
set -ogq @thm_primary "#696224"
set -ogq @thm_primary_light "#706512"
set -ogq @thm_secondary "#296352"
set -ogq @thm_prefix "#5107ab"
set -ogq @thm_fg "#1c1c13"

# Surfaces and overlays
set -ogq @thm_core "#fcf6ee"
set -ogq @thm_crust "#fbf3e7"
set -ogq @thm_mantle "#f9ecda"
set -ogq @thm_surface "#f3daba"
set -ogq @thm_visual "#e1c99d"

# General
set -ogq @thm_red "#c11313"
set -ogq @thm_orange "#8e5215"
set -ogq @thm_yellow "#696223"
set -ogq @thm_green "#3d6b39"
set -ogq @thm_teal "#396a5c"
set -ogq @thm_blue "#1661ae"
set -ogq @thm_indigo "#7f30de"
