# vim:set ft=tmux:
## name: Oasis Starlight Light 1
## author: uhs-robert

# Main
set -ogq @thm_primary_strong "#1e75b1"
set -ogq @thm_primary "#064687"
set -ogq @thm_primary_light "#05407d"
set -ogq @thm_secondary "#786e14"
set -ogq @thm_prefix "#ab0707"
set -ogq @thm_fg "#1e1e14"

# Surfaces and overlays
set -ogq @thm_core "#faf9f5"
set -ogq @thm_crust "#f7f6f0"
set -ogq @thm_mantle "#f2f0e6"
set -ogq @thm_surface "#e6e1cc"
set -ogq @thm_visual "#dacfa4"

# General
set -ogq @thm_red "#c31414"
set -ogq @thm_orange "#905315"
set -ogq @thm_yellow "#6a6323"
set -ogq @thm_green "#3e6d39"
set -ogq @thm_teal "#3a6b5e"
set -ogq @thm_blue "#1663b1"
set -ogq @thm_indigo "#8132de"
