# vim:set ft=tmux:
## name: Oasis Mirage Light 1
## author: uhs-robert

# Main
set -ogq @thm_primary_strong "#418d7a"
set -ogq @thm_primary "#2a6252"
set -ogq @thm_primary_light "#265c4d"
set -ogq @thm_secondary "#81460c"
set -ogq @thm_prefix "#5107ab"
set -ogq @thm_fg "#1c1c14"

# Surfaces and overlays
set -ogq @thm_core "#effaf8"
set -ogq @thm_crust "#e9f8f5"
set -ogq @thm_mantle "#def5f0"
set -ogq @thm_surface "#c0ebe4"
set -ogq @thm_visual "#9fe0d7"

# General
set -ogq @thm_red "#c21313"
set -ogq @thm_orange "#8f5215"
set -ogq @thm_yellow "#696323"
set -ogq @thm_green "#3d6c39"
set -ogq @thm_teal "#396a5d"
set -ogq @thm_blue "#1662af"
set -ogq @thm_indigo "#8030de"
