# vim:set ft=tmux:
## name: Oasis Starlight Light 5
## author: uhs-robert

# Main
set -ogq @thm_primary_strong "#135f93"
set -ogq @thm_primary "#003263"
set -ogq @thm_primary_light "#002c59"
set -ogq @thm_secondary "#58500b"
set -ogq @thm_prefix "#8a0000"
set -ogq @thm_fg "#181811"

# Surfaces and overlays
set -ogq @thm_core "#ebe5d5"
set -ogq @thm_crust "#e9e2d0"
set -ogq @thm_mantle "#e4dbc5"
set -ogq @thm_surface "#d7cbac"
set -ogq @thm_visual "#dacfa4"

# General
set -ogq @thm_red "#ae1111"
set -ogq @thm_orange "#804913"
set -ogq @thm_yellow "#5e581f"
set -ogq @thm_green "#366033"
set -ogq @thm_teal "#345e52"
set -ogq @thm_blue "#13579b"
set -ogq @thm_indigo "#7322d1"
