# vim:set ft=tmux:
## name: Oasis Moonlight Light 5
## author: uhs-robert

# Main
set -ogq @thm_primary_strong "#315275"
set -ogq @thm_primary "#1e3146"
set -ogq @thm_primary_light "#1a2d3f"
set -ogq @thm_secondary "#58500b"
set -ogq @thm_prefix "#8a0000"
set -ogq @thm_fg "#181811"

# Surfaces and overlays
set -ogq @thm_core "#ddd8c5"
set -ogq @thm_crust "#dad5c0"
set -ogq @thm_mantle "#d5ceb7"
set -ogq @thm_surface "#c6be9e"
set -ogq @thm_visual "#e1b69d"

# General
set -ogq @thm_red "#9e0f0f"
set -ogq @thm_orange "#744211"
set -ogq @thm_yellow "#55501c"
set -ogq @thm_green "#31572e"
set -ogq @thm_teal "#2f564a"
set -ogq @thm_blue "#114f8d"
set -ogq @thm_indigo "#691fbe"
