# vim:set ft=tmux:
## name: Oasis Night Light 5
## author: uhs-robert

# Main
set -ogq @thm_strong_primary "#2d4c6c"
set -ogq @thm_primary "#263f5a"
set -ogq @thm_light_primary "#1e3448"
set -ogq @thm_secondary "#696221"
set -ogq @thm_prefix "#8a0000"
set -ogq @thm_fg "#4b3b28"

# Surfaces and overlays
set -ogq @thm_core "#e0cfa3"
set -ogq @thm_mantle "#ddc998"
set -ogq @thm_surface "#d5bd81"
set -ogq @thm_visual "#e1b69d"

# General
set -ogq @thm_red "#950e0e"
set -ogq @thm_orange "#6d3e10"
set -ogq @thm_yellow "#504b1a"
set -ogq @thm_green "#891317"
set -ogq @thm_teal "#29504a"
set -ogq @thm_blue "#104b84"
set -ogq @thm_indigo "#621db3"
