# vim:set ft=tmux:
## name: Oasis Lagoon Light 5
## author: uhs-robert

# Main
set -ogq @thm_primary_strong "#135f93"
set -ogq @thm_primary "#003263"
set -ogq @thm_primary_light "#002c59"
set -ogq @thm_secondary "#5f3105"
set -ogq @thm_prefix "#8a0000"
set -ogq @thm_fg "#181811"

# Surfaces and overlays
set -ogq @thm_core "#c1daf6"
set -ogq @thm_crust "#bad6f5"
set -ogq @thm_mantle "#adcef3"
set -ogq @thm_surface "#8cbaee"
set -ogq @thm_visual "#9fcae0"

# General
set -ogq @thm_red "#9e0f0f"
set -ogq @thm_orange "#734211"
set -ogq @thm_yellow "#554f1c"
set -ogq @thm_green "#31572e"
set -ogq @thm_teal "#2f554a"
set -ogq @thm_blue "#114f8c"
set -ogq @thm_indigo "#681fbd"
