# vim:set ft=tmux:
## name: Oasis Abyss Light 5
## author: uhs-robert

# Main
set -ogq @thm_primary_strong "#736e33"
set -ogq @thm_primary "#4c4717"
set -ogq @thm_primary_light "#4f480a"
set -ogq @thm_secondary "#630000"
set -ogq @thm_prefix "#296624"
set -ogq @thm_fg "#181811"

# Surfaces and overlays
set -ogq @thm_core "#c9c9c9"
set -ogq @thm_crust "#c5c5c5"
set -ogq @thm_mantle "#bebebe"
set -ogq @thm_surface "#aaaaaa"
set -ogq @thm_visual "#e1c99d"

# General
set -ogq @thm_red "#8c0e0e"
set -ogq @thm_orange "#663a0f"
set -ogq @thm_yellow "#4b4619"
set -ogq @thm_green "#2b4d28"
set -ogq @thm_teal "#294b41"
set -ogq @thm_blue "#0f467c"
set -ogq @thm_indigo "#5d1ba8"
