# vim:set ft=tmux:
## name: Oasis Night Light 5
## author: uhs-robert

# Main
set -ogq @thm_primary_strong "#315275"
set -ogq @thm_primary "#1e3146"
set -ogq @thm_primary_light "#1a2d3f"
set -ogq @thm_secondary "#58500b"
set -ogq @thm_prefix "#8a0000"
set -ogq @thm_fg "#181811"

# Surfaces and overlays
set -ogq @thm_core "#b7d5f0"
set -ogq @thm_crust "#b1d1ef"
set -ogq @thm_mantle "#a4caec"
set -ogq @thm_surface "#84b7e6"
set -ogq @thm_visual "#e1b69d"

# General
set -ogq @thm_red "#960f0f"
set -ogq @thm_orange "#6e3f10"
set -ogq @thm_yellow "#504b1b"
set -ogq @thm_green "#2f522b"
set -ogq @thm_teal "#2c5146"
set -ogq @thm_blue "#104b86"
set -ogq @thm_indigo "#631db5"
