# vim:set ft=tmux:
## name: Oasis Mirage Light 5
## author: uhs-robert

# Main
set -ogq @thm_primary_strong "#327463"
set -ogq @thm_primary "#1c473b"
set -ogq @thm_primary_light "#184135"
set -ogq @thm_secondary "#5f3105"
set -ogq @thm_prefix "#3e008a"
set -ogq @thm_fg "#181811"

# Surfaces and overlays
set -ogq @thm_core "#c1eae6"
set -ogq @thm_crust "#bbe8e4"
set -ogq @thm_mantle "#b0e4df"
set -ogq @thm_surface "#93dbd4"
set -ogq @thm_visual "#9fe0d7"

# General
set -ogq @thm_red "#aa1010"
set -ogq @thm_orange "#7d4712"
set -ogq @thm_yellow "#5c561e"
set -ogq @thm_green "#355e31"
set -ogq @thm_teal "#325c50"
set -ogq @thm_blue "#125598"
set -ogq @thm_indigo "#7021cc"
