# vim:set ft=tmux:
## name: Oasis Sol Dark
## author: uhs-robert

# Main
set -ogq @thm_primary_strong "#e26e6e"
set -ogq @thm_primary "#ff7979"
set -ogq @thm_primary_light "#ffa0a0"
set -ogq @thm_secondary "#f8b471"
set -ogq @thm_prefix "#7fcf78"
set -ogq @thm_fg "#f5f5dc"

# Surfaces and overlays
set -ogq @thm_core "#271311"
set -ogq @thm_crust "#1f0f0e"
set -ogq @thm_mantle "#2f1c18"
set -ogq @thm_surface "#432823"
set -ogq @thm_visual "#666666"

# General
set -ogq @thm_red "#ff7979"
set -ogq @thm_orange "#f8b471"
set -ogq @thm_yellow "#f0e68c"
set -ogq @thm_green "#7fcf78"
set -ogq @thm_teal "#8ad3be"
set -ogq @thm_blue "#81c0ff"
set -ogq @thm_indigo "#c695ff"
