# vim:set ft=tmux:
## name: Oasis Canyon Dark
## author: uhs-robert

# Main
set -ogq @thm_primary_strong "#ffa34d"
set -ogq @thm_primary "#f9af96"
set -ogq @thm_primary_light "#f8c471"
set -ogq @thm_secondary "#94d0fe"
set -ogq @thm_prefix "#ff9090"
set -ogq @thm_fg "#f5f5dc"

# Surfaces and overlays
set -ogq @thm_core "#261612"
set -ogq @thm_crust "#1f120e"
set -ogq @thm_mantle "#35231d"
set -ogq @thm_surface "#483228"
set -ogq @thm_visual "#666666"

# General
set -ogq @thm_red "#ff7979"
set -ogq @thm_orange "#f8b471"
set -ogq @thm_yellow "#f0e68c"
set -ogq @thm_green "#7fcf78"
set -ogq @thm_teal "#8ad3be"
set -ogq @thm_blue "#81c0ff"
set -ogq @thm_indigo "#c695ff"
