# vim:set ft=tmux:
## name: Oasis Moonlight Dark
## author: uhs-robert

# Main
set -ogq @thm_primary_strong "#5d8bbb"
set -ogq @thm_primary "#7fa3c9"
set -ogq @thm_primary_light "#b0c8de"
set -ogq @thm_secondary "#f0e68c"
set -ogq @thm_prefix "#ffa0a0"
set -ogq @thm_fg "#f5f5dc"

# Surfaces and overlays
set -ogq @thm_core "#0c0e13"
set -ogq @thm_crust "#070a0e"
set -ogq @thm_mantle "#141c24"
set -ogq @thm_surface "#1e2a38"
set -ogq @thm_visual "#666666"

# General
set -ogq @thm_red "#ff7979"
set -ogq @thm_orange "#f8b471"
set -ogq @thm_yellow "#f0e68c"
set -ogq @thm_green "#7fcf78"
set -ogq @thm_teal "#8ad3be"
set -ogq @thm_blue "#81c0ff"
set -ogq @thm_indigo "#c695ff"
