# vim:set ft=tmux:
## name: Oasis Dune Dark
## author: uhs-robert

# Main
set -ogq @thm_primary_strong "#bdb76b"
set -ogq @thm_primary "#d8cf7f"
set -ogq @thm_primary_light "#f3ea9f"
set -ogq @thm_secondary "#d89a72"
set -ogq @thm_prefix "#69c3aa"
set -ogq @thm_fg "#f5f5dc"

# Surfaces and overlays
set -ogq @thm_core "#27211b"
set -ogq @thm_crust "#211d17"
set -ogq @thm_mantle "#322a24"
set -ogq @thm_surface "#463e34"
set -ogq @thm_visual "#666666"

# General
set -ogq @thm_red "#ff7979"
set -ogq @thm_orange "#f8b471"
set -ogq @thm_yellow "#f0e68c"
set -ogq @thm_green "#7fcf78"
set -ogq @thm_teal "#8ad3be"
set -ogq @thm_blue "#81c0ff"
set -ogq @thm_indigo "#c695ff"
