# vim:set ft=tmux:
## name: Oasis Mirage Dark
## author: uhs-robert

# Main
set -ogq @thm_primary_strong "#55b69d"
set -ogq @thm_primary "#69c3aa"
set -ogq @thm_primary_light "#8ad3be"
set -ogq @thm_secondary "#f8b471"
set -ogq @thm_prefix "#d2adff"
set -ogq @thm_fg "#f5f5dc"

# Surfaces and overlays
set -ogq @thm_core "#111c22"
set -ogq @thm_crust "#0d161c"
set -ogq @thm_mantle "#18252a"
set -ogq @thm_surface "#21333b"
set -ogq @thm_visual "#666666"

# General
set -ogq @thm_red "#ff7979"
set -ogq @thm_orange "#f8b471"
set -ogq @thm_yellow "#f0e68c"
set -ogq @thm_green "#7fcf78"
set -ogq @thm_teal "#8ad3be"
set -ogq @thm_blue "#81c0ff"
set -ogq @thm_indigo "#c695ff"
