# vim:set ft=tmux:
## name: Oasis Starlight Light 2
## author: uhs-robert

# Main
set -ogq @thm_primary_strong "#1b70aa"
set -ogq @thm_primary "#04417e"
set -ogq @thm_primary_light "#043b74"
set -ogq @thm_secondary "#706712"
set -ogq @thm_prefix "#a30505"
set -ogq @thm_fg "#1d1d14"

# Surfaces and overlays
set -ogq @thm_core "#faf8f4"
set -ogq @thm_crust "#f8f5ef"
set -ogq @thm_mantle "#f3eee4"
set -ogq @thm_surface "#e7ddca"
set -ogq @thm_visual "#dacfa4"

# General
set -ogq @thm_red "#c21414"
set -ogq @thm_orange "#905215"
set -ogq @thm_yellow "#6a6323"
set -ogq @thm_green "#3d6c3a"
set -ogq @thm_teal "#3a6a5c"
set -ogq @thm_blue "#1662b0"
set -ogq @thm_indigo "#8031dd"
