# vim:set ft=tmux:
## name: Oasis Canyon Light 2
## author: uhs-robert

# Main
set -ogq @thm_primary_strong "#a36021"
set -ogq @thm_primary "#78410a"
set -ogq @thm_primary_light "#6f4808"
set -ogq @thm_secondary "#05497d"
set -ogq @thm_prefix "#a30505"
set -ogq @thm_fg "#181811"

# Surfaces and overlays
set -ogq @thm_core "#f1dbc9"
set -ogq @thm_crust "#efd7c3"
set -ogq @thm_mantle "#eccfb7"
set -ogq @thm_surface "#e4bb98"
set -ogq @thm_visual "#e1b69d"

# General
set -ogq @thm_red "#a61111"
set -ogq @thm_orange "#7a4612"
set -ogq @thm_yellow "#5a541e"
set -ogq @thm_green "#345c31"
set -ogq @thm_teal "#315a4e"
set -ogq @thm_blue "#125395"
set -ogq @thm_indigo "#6e21c8"
