# vim:set ft=tmux:
## name: Oasis Scorpion Light 2
## author: uhs-robert

# Main
set -ogq @thm_primary_strong "#8e8736"
set -ogq @thm_primary "#706712"
set -ogq @thm_primary_light "#685e10"
set -ogq @thm_secondary "#77240b"
set -ogq @thm_prefix "#357a2f"
set -ogq @thm_fg "#181811"

# Surfaces and overlays
set -ogq @thm_core "#f6d9d0"
set -ogq @thm_crust "#f5d4ca"
set -ogq @thm_mantle "#f2c9bd"
set -ogq @thm_surface "#ecaf9d"
set -ogq @thm_visual "#e1b69d"

# General
set -ogq @thm_red "#a61111"
set -ogq @thm_orange "#7a4612"
set -ogq @thm_yellow "#5a541e"
set -ogq @thm_green "#345c31"
set -ogq @thm_teal "#315a4e"
set -ogq @thm_blue "#125496"
set -ogq @thm_indigo "#6e21c8"
