# vim:set ft=tmux:
## name: Oasis Night Light 2
## author: uhs-robert

# Main
set -ogq @thm_primary_strong "#3c6188"
set -ogq @thm_primary "#28405a"
set -ogq @thm_primary_light "#253d53"
set -ogq @thm_secondary "#706712"
set -ogq @thm_prefix "#a30505"
set -ogq @thm_fg "#181811"

# Surfaces and overlays
set -ogq @thm_core "#e4edf7"
set -ogq @thm_crust "#dee9f5"
set -ogq @thm_mantle "#d2e2f1"
set -ogq @thm_surface "#b4cfe9"
set -ogq @thm_visual "#e1b69d"

# General
set -ogq @thm_red "#b51212"
set -ogq @thm_orange "#854d14"
set -ogq @thm_yellow "#625c21"
set -ogq @thm_green "#396435"
set -ogq @thm_teal "#356355"
set -ogq @thm_blue "#145ba3"
set -ogq @thm_indigo "#7824da"
