# vim:set ft=tmux:
## name: Oasis Cactus Light 2
## author: uhs-robert

# Main
set -ogq @thm_primary_strong "#467e49"
set -ogq @thm_primary "#2e5430"
set -ogq @thm_primary_light "#294f2b"
set -ogq @thm_secondary "#3b047e"
set -ogq @thm_prefix "#a30505"
set -ogq @thm_fg "#181811"

# Surfaces and overlays
set -ogq @thm_core "#e7f4eb"
set -ogq @thm_crust "#e2f2e7"
set -ogq @thm_mantle "#d7edde"
set -ogq @thm_surface "#bde1c8"
set -ogq @thm_visual "#a4dac0"

# General
set -ogq @thm_red "#ba1313"
set -ogq @thm_orange "#8a4f14"
set -ogq @thm_yellow "#655e22"
set -ogq @thm_green "#3b6737"
set -ogq @thm_teal "#376658"
set -ogq @thm_blue "#155ea8"
set -ogq @thm_indigo "#7b29dc"
