# vim:set ft=tmux:
## name: Oasis Moonlight Light 2
## author: uhs-robert

# Main
set -ogq @thm_primary_strong "#3c6188"
set -ogq @thm_primary "#28405a"
set -ogq @thm_primary_light "#253d53"
set -ogq @thm_secondary "#706712"
set -ogq @thm_prefix "#a30505"
set -ogq @thm_fg "#181811"

# Surfaces and overlays
set -ogq @thm_core "#eeebe2"
set -ogq @thm_crust "#ebe8dd"
set -ogq @thm_mantle "#e6e1d4"
set -ogq @thm_surface "#d7d0bb"
set -ogq @thm_visual "#e1b69d"

# General
set -ogq @thm_red "#b41212"
set -ogq @thm_orange "#854c13"
set -ogq @thm_yellow "#615b21"
set -ogq @thm_green "#396435"
set -ogq @thm_teal "#356255"
set -ogq @thm_blue "#145ba2"
set -ogq @thm_indigo "#7724d9"
