# vim:set ft=tmux:
## name: Oasis Mirage Light 2
## author: uhs-robert

# Main
set -ogq @thm_primary_strong "#3d8774"
set -ogq @thm_primary "#275b4d"
set -ogq @thm_primary_light "#225547"
set -ogq @thm_secondary "#78410a"
set -ogq @thm_prefix "#4c05a3"
set -ogq @thm_fg "#181811"

# Surfaces and overlays
set -ogq @thm_core "#e3f6f4"
set -ogq @thm_crust "#ddf4f2"
set -ogq @thm_mantle "#d2f0ed"
set -ogq @thm_surface "#b5e7e2"
set -ogq @thm_visual "#9fe0d7"

# General
set -ogq @thm_red "#bc1313"
set -ogq @thm_orange "#8a4f14"
set -ogq @thm_yellow "#665f22"
set -ogq @thm_green "#3b6837"
set -ogq @thm_teal "#386759"
set -ogq @thm_blue "#155fa9"
set -ogq @thm_indigo "#7c2bdc"
