# vim:set ft=tmux:
## name: Oasis Scorpion Light 2
## author: uhs-robert

# Main
set -ogq @thm_strong_primary "#857e33"
set -ogq @thm_primary "#887d16"
set -ogq @thm_light_primary "#736812"
set -ogq @thm_secondary "#9a2e0e"
set -ogq @thm_prefix "#357a2f"
set -ogq @thm_fg "#644a40"

# Surfaces and overlays
set -ogq @thm_core "#f8ece7"
set -ogq @thm_mantle "#f5e3db"
set -ogq @thm_surface "#eed0c3"
set -ogq @thm_visual "#e19d9d"

# General
set -ogq @thm_red "#b81212"
set -ogq @thm_orange "#884e14"
set -ogq @thm_yellow "#645d21"
set -ogq @thm_green "#ab181d"
set -ogq @thm_teal "#33645d"
set -ogq @thm_blue "#145ca5"
set -ogq @thm_indigo "#7a26db"
