# vim:set ft=tmux:
## name: Oasis Midnight Light 2
## author: uhs-robert

# Main
set -ogq @thm_primary_strong "#86803f"
set -ogq @thm_primary "#625b20"
set -ogq @thm_primary_light "#685e10"
set -ogq @thm_secondary "#7e0404"
set -ogq @thm_prefix "#357a2f"
set -ogq @thm_fg "#181811"

# Surfaces and overlays
set -ogq @thm_core "#e3e6ee"
set -ogq @thm_crust "#dee2eb"
set -ogq @thm_mantle "#d5d9e5"
set -ogq @thm_surface "#bdc4d7"
set -ogq @thm_visual "#e1c99d"

# General
set -ogq @thm_red "#ae1212"
set -ogq @thm_orange "#804913"
set -ogq @thm_yellow "#5f5820"
set -ogq @thm_green "#376033"
set -ogq @thm_teal "#335f52"
set -ogq @thm_blue "#13589d"
set -ogq @thm_indigo "#7323d2"
