# vim:set ft=tmux:
## name: Oasis Starlight Light 3
## author: uhs-robert

# Main
set -ogq @thm_primary_strong "#186aa2"
set -ogq @thm_primary "#023c75"
set -ogq @thm_primary_light "#02366b"
set -ogq @thm_secondary "#685f10"
set -ogq @thm_prefix "#9b0303"
set -ogq @thm_fg "#181811"

# Surfaces and overlays
set -ogq @thm_core "#f5f2ea"
set -ogq @thm_crust "#f3efe5"
set -ogq @thm_mantle "#eee8da"
set -ogq @thm_surface "#e1d8c1"
set -ogq @thm_visual "#dacfa4"

# General
set -ogq @thm_red "#bc1313"
set -ogq @thm_orange "#8b4f15"
set -ogq @thm_yellow "#665f22"
set -ogq @thm_green "#3b6837"
set -ogq @thm_teal "#386659"
set -ogq @thm_blue "#155fa8"
set -ogq @thm_indigo "#7d2adc"
