# vim:set ft=tmux:
## name: Oasis Abyss Light 3
## author: uhs-robert

# Main
set -ogq @thm_primary_strong "#7f7a3b"
set -ogq @thm_primary "#5b541d"
set -ogq @thm_primary_light "#60570e"
set -ogq @thm_secondary "#750202"
set -ogq @thm_prefix "#31732b"
set -ogq @thm_fg "#181811"

# Surfaces and overlays
set -ogq @thm_core "#d8d8d8"
set -ogq @thm_crust "#d4d4d4"
set -ogq @thm_mantle "#cdcdcd"
set -ogq @thm_surface "#b9b9b9"
set -ogq @thm_visual "#e1c99d"

# General
set -ogq @thm_red "#9e1010"
set -ogq @thm_orange "#744211"
set -ogq @thm_yellow "#554f1c"
set -ogq @thm_green "#31572e"
set -ogq @thm_teal "#2f564a"
set -ogq @thm_blue "#11508d"
set -ogq @thm_indigo "#691fbe"
