# vim:set ft=tmux:
## name: Oasis Desert Light 3
## author: uhs-robert

# Main
set -ogq @thm_primary_strong "#7f7a3b"
set -ogq @thm_primary "#685f10"
set -ogq @thm_primary_light "#60570e"
set -ogq @thm_secondary "#750202"
set -ogq @thm_prefix "#31732b"
set -ogq @thm_fg "#181811"

# Surfaces and overlays
set -ogq @thm_core "#f3edcf"
set -ogq @thm_crust "#f1ebc9"
set -ogq @thm_mantle "#eee6bd"
set -ogq @thm_surface "#e7db9e"
set -ogq @thm_visual "#e1c99d"

# General
set -ogq @thm_red "#b61212"
set -ogq @thm_orange "#864d14"
set -ogq @thm_yellow "#635c21"
set -ogq @thm_green "#396535"
set -ogq @thm_teal "#366356"
set -ogq @thm_blue "#145ca2"
set -ogq @thm_indigo "#7824db"
