# vim:set ft=tmux:
## name: Oasis Mirage Light 3
## author: uhs-robert

# Main
set -ogq @thm_primary_strong "#39816e"
set -ogq @thm_primary "#235547"
set -ogq @thm_primary_light "#1f4f41"
set -ogq @thm_secondary "#703c08"
set -ogq @thm_prefix "#48039b"
set -ogq @thm_fg "#181811"

# Surfaces and overlays
set -ogq @thm_core "#d8f2ef"
set -ogq @thm_crust "#d2f0ed"
set -ogq @thm_mantle "#c7ece8"
set -ogq @thm_surface "#aae3dc"
set -ogq @thm_visual "#9fe0d7"

# General
set -ogq @thm_red "#b61212"
set -ogq @thm_orange "#864d14"
set -ogq @thm_yellow "#635c21"
set -ogq @thm_green "#396535"
set -ogq @thm_teal "#366356"
set -ogq @thm_blue "#145ca3"
set -ogq @thm_indigo "#7824db"
