# vim:set ft=tmux:
## name: Oasis Scorpion Light 3
## author: uhs-robert

# Main
set -ogq @thm_strong_primary "#7e782f"
set -ogq @thm_primary "#817613"
set -ogq @thm_light_primary "#6b6110"
set -ogq @thm_secondary "#922b0c"
set -ogq @thm_prefix "#31732b"
set -ogq @thm_fg "#5c443b"

# Surfaces and overlays
set -ogq @thm_core "#f7ded4"
set -ogq @thm_mantle "#f5d4c7"
set -ogq @thm_surface "#f0c0ad"
set -ogq @thm_visual "#e19d9d"

# General
set -ogq @thm_red "#ab1111"
set -ogq @thm_orange "#7e4813"
set -ogq @thm_yellow "#5d561f"
set -ogq @thm_green "#9e171b"
set -ogq @thm_teal "#2f5d56"
set -ogq @thm_blue "#135699"
set -ogq @thm_indigo "#7121ce"
