# vim:set ft=tmux:
## name: Oasis Sol Light 3
## author: uhs-robert

# Main
set -ogq @thm_primary_strong "#8c2e2e"
set -ogq @thm_primary "#750202"
set -ogq @thm_primary_light "#6b0202"
set -ogq @thm_secondary "#703c08"
set -ogq @thm_prefix "#31732b"
set -ogq @thm_fg "#181811"

# Surfaces and overlays
set -ogq @thm_core "#f2c4c4"
set -ogq @thm_crust "#f1bebe"
set -ogq @thm_mantle "#eeb1b1"
set -ogq @thm_surface "#e79292"
set -ogq @thm_visual "#e19d9d"

# General
set -ogq @thm_red "#930f0f"
set -ogq @thm_orange "#6b3e10"
set -ogq @thm_yellow "#4f4a1a"
set -ogq @thm_green "#2e512a"
set -ogq @thm_teal "#2b4f45"
set -ogq @thm_blue "#104a83"
set -ogq @thm_indigo "#611db1"
