# vim:set ft=tmux:
## name: Oasis Twilight Light 3
## author: uhs-robert

# Main
set -ogq @thm_primary_strong "#984222"
set -ogq @thm_primary "#6f2009"
set -ogq @thm_primary_light "#672107"
set -ogq @thm_secondary "#360275"
set -ogq @thm_prefix "#897e15"
set -ogq @thm_fg "#181811"

# Surfaces and overlays
set -ogq @thm_core "#eadff4"
set -ogq @thm_crust "#e6d9f2"
set -ogq @thm_mantle "#dfceee"
set -ogq @thm_surface "#ccb1e4"
set -ogq @thm_visual "#e1b69d"

# General
set -ogq @thm_red "#ab1111"
set -ogq @thm_orange "#7e4813"
set -ogq @thm_yellow "#5d561f"
set -ogq @thm_green "#365f32"
set -ogq @thm_teal "#335d51"
set -ogq @thm_blue "#135699"
set -ogq @thm_indigo "#7121ce"
