# vim:set ft=tmux:
## name: Oasis Dune Light 3
## author: uhs-robert

# Main
set -ogq @thm_primary_strong "#7f703b"
set -ogq @thm_primary "#5b541d"
set -ogq @thm_primary_light "#60570d"
set -ogq @thm_secondary "#225646"
set -ogq @thm_prefix "#48039b"
set -ogq @thm_fg "#181811"

# Surfaces and overlays
set -ogq @thm_core "#f7e9d4"
set -ogq @thm_crust "#f6e6ce"
set -ogq @thm_mantle "#f3dfc1"
set -ogq @thm_surface "#edcfa0"
set -ogq @thm_visual "#e1c99d"

# General
set -ogq @thm_red "#b41212"
set -ogq @thm_orange "#854c14"
set -ogq @thm_yellow "#615b20"
set -ogq @thm_green "#386334"
set -ogq @thm_teal "#366255"
set -ogq @thm_blue "#145ba1"
set -ogq @thm_indigo "#7723d9"
