# vim:set ft=tmux:
## name: Oasis Dune Light 4
## author: uhs-robert

# Main
set -ogq @thm_primary_strong "#796b37"
set -ogq @thm_primary "#534e1a"
set -ogq @thm_primary_light "#58500c"
set -ogq @thm_secondary "#553018"
set -ogq @thm_prefix "#2b6958"
set -ogq @thm_fg "#181811"

# Surfaces and overlays
set -ogq @thm_core "#f5e2c7"
set -ogq @thm_crust "#f4dfc1"
set -ogq @thm_mantle "#f2d8b4"
set -ogq @thm_surface "#ecc793"
set -ogq @thm_visual "#e1c99d"

# General
set -ogq @thm_red "#ad1212"
set -ogq @thm_orange "#7f4913"
set -ogq @thm_yellow "#5e571f"
set -ogq @thm_green "#366033"
set -ogq @thm_teal "#335e52"
set -ogq @thm_blue "#13579a"
set -ogq @thm_indigo "#7222d0"
