# vim:set ft=tmux:
## name: Oasis Scorpion Light 4
## author: uhs-robert

# Main
set -ogq @thm_primary_strong "#3e763a"
set -ogq @thm_primary "#21501d"
set -ogq @thm_primary_light "#1d4d16"
set -ogq @thm_secondary "#661d07"
set -ogq @thm_prefix "#716923"
set -ogq @thm_fg "#181811"

# Surfaces and overlays
set -ogq @thm_core "#f2c5b6"
set -ogq @thm_crust "#f1c0b0"
set -ogq @thm_mantle "#efb6a3"
set -ogq @thm_surface "#e99c82"
set -ogq @thm_visual "#e1b69d"

# General
set -ogq @thm_red "#930f0f"
set -ogq @thm_orange "#6c3e10"
set -ogq @thm_yellow "#4f4a1a"
set -ogq @thm_green "#2e512b"
set -ogq @thm_teal "#2b4f45"
set -ogq @thm_blue "#104a83"
set -ogq @thm_indigo "#611db0"
