# vim:set ft=tmux:
## name: Oasis Dune Light 4
## author: uhs-robert

# Main
set -ogq @thm_strong_primary "#706c33"
set -ogq @thm_primary "#796e11"
set -ogq @thm_light_primary "#64590d"
set -ogq @thm_secondary "#2c685f"
set -ogq @thm_prefix "#430192"
set -ogq @thm_fg "#4f4d44"

# Surfaces and overlays
set -ogq @thm_core "#f0e9d1"
set -ogq @thm_mantle "#ece3c5"
set -ogq @thm_surface "#e5d8ae"
set -ogq @thm_visual "#dacfa4"

# General
set -ogq @thm_red "#b21212"
set -ogq @thm_orange "#834b13"
set -ogq @thm_yellow "#605a20"
set -ogq @thm_green "#a5181c"
set -ogq @thm_teal "#316159"
set -ogq @thm_blue "#135a9f"
set -ogq @thm_indigo "#7623d6"
