# vim:set ft=tmux:
## name: Oasis Abyss Light 4
## author: uhs-robert

# Main
set -ogq @thm_strong_primary "#706c33"
set -ogq @thm_primary "#796e11"
set -ogq @thm_light_primary "#635a0d"
set -ogq @thm_secondary "#920101"
set -ogq @thm_prefix "#2d6c27"
set -ogq @thm_fg "#4e473f"

# Surfaces and overlays
set -ogq @thm_core "#f5ddc7"
set -ogq @thm_mantle "#f3d5ba"
set -ogq @thm_surface "#eec5a0"
set -ogq @thm_visual "#e19d9d"

# General
set -ogq @thm_red "#a91111"
set -ogq @thm_orange "#7c4712"
set -ogq @thm_yellow "#5b551f"
set -ogq @thm_green "#9c171b"
set -ogq @thm_teal "#2f5c55"
set -ogq @thm_blue "#125597"
set -ogq @thm_indigo "#6f21cb"
