# vim:set ft=tmux:
## name: Oasis Starlight Light 4
## author: uhs-robert

# Main
set -ogq @thm_primary_strong "#15659b"
set -ogq @thm_primary "#01376d"
set -ogq @thm_primary_light "#013162"
set -ogq @thm_secondary "#60580d"
set -ogq @thm_prefix "#920101"
set -ogq @thm_fg "#181811"

# Surfaces and overlays
set -ogq @thm_core "#f0ece0"
set -ogq @thm_crust "#eee9db"
set -ogq @thm_mantle "#e9e3d1"
set -ogq @thm_surface "#dcd3b7"
set -ogq @thm_visual "#dacfa4"

# General
set -ogq @thm_red "#b51212"
set -ogq @thm_orange "#864c14"
set -ogq @thm_yellow "#625c21"
set -ogq @thm_green "#396435"
set -ogq @thm_teal "#356356"
set -ogq @thm_blue "#145ba2"
set -ogq @thm_indigo "#7824da"
