# vim:set ft=tmux:
## name: Oasis Luna Light 4
## author: uhs-robert

# Main
set -ogq @thm_strong_primary "#706c33"
set -ogq @thm_primary "#796e11"
set -ogq @thm_light_primary "#635a0d"
set -ogq @thm_secondary "#450192"
set -ogq @thm_prefix "#136881"
set -ogq @thm_fg "#42376c"

# Surfaces and overlays
set -ogq @thm_core "#d5cef3"
set -ogq @thm_mantle "#cac2f0"
set -ogq @thm_surface "#b5a9ea"
set -ogq @thm_visual "#e19d9d"

# General
set -ogq @thm_red "#970f0f"
set -ogq @thm_orange "#6f3f10"
set -ogq @thm_yellow "#514c1b"
set -ogq @thm_green "#8b1418"
set -ogq @thm_teal "#2a524c"
set -ogq @thm_blue "#104c87"
set -ogq @thm_indigo "#641eb6"
