# vim:set ft=tmux:
## name: Oasis Rose Light 4
## author: uhs-robert

# Main
set -ogq @thm_primary_strong "#87294e"
set -ogq @thm_primary "#551830"
set -ogq @thm_primary_light "#4f152c"
set -ogq @thm_secondary "#264827"
set -ogq @thm_prefix "#2a6a57"
set -ogq @thm_fg "#181811"

# Surfaces and overlays
set -ogq @thm_core "#f0cae1"
set -ogq @thm_crust "#eec4de"
set -ogq @thm_mantle "#ebb8d7"
set -ogq @thm_surface "#e39ac6"
set -ogq @thm_visual "#dba3c6"

# General
set -ogq @thm_red "#9a1010"
set -ogq @thm_orange "#714111"
set -ogq @thm_yellow "#534d1c"
set -ogq @thm_green "#30552d"
set -ogq @thm_teal "#2d5348"
set -ogq @thm_blue "#114d89"
set -ogq @thm_indigo "#661fb9"
